name: Build and test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    env: 
      NEXT_PUBLIC_BASE_PATH:
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
      API_URL: ${{vars.API_URL}}
      FRONTEND_URL: ${{vars.FRONTEND_URL}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --prod
          npm run test --if-present