name: NO TESTS Build and deploy to Azure Web App - lecti-front

on:
  push:
    branches:
      - main
      - qa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    env: 
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
      API_URL: ${{vars.API_URL}}
      NEXT_PUBLIC_API_URL: ${{vars.API_URL}}
      FRONTEND_URL: ${{vars.FRONTEND_URL}}
      NEXT_PUBLIC_FRONTEND_URL: ${{vars.FRONTEND_URL}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --prod

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1FD9ADC84EF344F9A2C287D93ED1D4AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B2630994A29741CE8DCD58CC222282C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B044D617390841AFA014DE890796FEB6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lecti-front'
          slot-name: 'Production'
          package: ./
          