name: Build and deploy to Azure Web App - lecti-front

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    env: 
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
      API_URL: ${{vars.API_URL}}
      FRONTEND_URL: ${{vars.FRONTEND_URL}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Delete local .env
        run: rm .env.local

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --prod
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6029D214B6CE4842B5284171DD2A28CF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F755B41AAC94D759CB8933380FFAA89 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EFBC215FDB64B67AF1C25CF512C99BC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lecti-front'
          slot-name: 'Production'
          package: ./